dataset license added
weaviate-tutorials/DEMO-multimodal-search pull request #3
Opened 2023-10-14 18:32 UTC by VishalPraneeth

2023-10-18 07:14 UTC, iamleonie requested changes

2023-10-18 07:14 UTC, iamleonie commented on README.md
> +Image dataset from [Unsplash](https://unsplash.com/)
Thanks for your contribution.
Would it be possible to add the link including attribution for 2 to 3 images to give this information more credibility? (We don't need it for all the images, just a few)

2023-10-19 06:03 UTC, VishalPraneeth commented on README.md
> +Image dataset from [Unsplash](https://unsplash.com/)
Yea sure!

2023-10-25 05:16 UTC, VishalPraneeth commented on README.md
> +Image dataset from [Unsplash](https://unsplash.com/)
@iamleonie can you review the changes please

2023-10-25 07:02 UTC, iamleonie commented
Hey @VishalPraneeth, did you see my request for one more change? 

> Thanks for the update!
Images that originate from iStock, we need to remove to avoid license issues. Could you please remove the lion image from the repository and update the README.md?

2023-10-25 14:19 UTC, VishalPraneeth commented
> Hey @VishalPraneeth, did you see my request for one more change?
> 
> > Thanks for the update!
> > Images that originate from iStock, we need to remove to avoid license issues. Could you please remove the lion image from the repository and update the README.md?

Yea sure,I'll do that

2023-10-26 06:57 UTC, iamleonie approved these changes

2023-10-26 06:57 UTC, iamleonie commented on README.md
> +[Lion image](static/Images/lion1.jfif) from [iStock](https://www.istockphoto.com/photo/lion-gm1005736050-271498835?utm_campaign=adp_photos_sponsored&utm_content=https%3A%2F%2Funsplash.com%2Fphotos%2F
Thanks for the update! 

Images that originate from iStock, we need to remove to avoid license issues. Could you please remove the lion image from the repository and update the README.md?

2023-10-26 06:57 UTC, iamleonie commented on README.md
> -Image dataset from [Unsplash](https://unsplash.com/)
I would leave the first line. Something like this:

> The images are sources from [Unsplash](https://unsplash.com/), for example:
(and then have the two examples from unsplash)

2023-10-26 06:57 UTC, merged

2023-10-26 06:57 UTC, iamleonie commented
Thank you for your contribution!